### ISSUE TITLE
Scaling and Throttling Questions

### ISSUE THREAD

**Issue by alnutile** [timescale/pgai#40]
Question, one of the challenges so far with https://github.com/LlmLaraHub/larallama has been throttling the requests to APIs like Ollama, OpenAi, Claude etc. 

For example with pgai if someone uploads 20-50 documents then the concern is that it will make 20+ concurrent requests to the backing API. For Ollama on my machine that would most likely cause a lot of timeouts or just a fail. As for OpenAi API it can results in issues of too many requests a minute.

Any thoughts on this factor as I consider replacing my existing code to move some of it into this? 

Thanks!

**Comment by jgpruitt** [comment]
At a high-level, instead of using a trigger to embed documents on insert, I would use a trigger to put an entry in a work queue table. Then, have a background job (use [pg_cron](https://github.com/citusdata/pg_cron) or [timescaledb jobs](https://docs.timescale.com/api/latest/actions/)) work the queue and implement rate limiting there.

**Comment by alnutile** [comment]
interesting pg_cron

**Comment by jgpruitt** [comment]
@alnutile Are you satisfied with this response? Can I close the issue?
